name: text-game-template
version: '1.0'
summary: A template for text-based game projects
description: |
  A template for text-based game projects.
base: core22
confinement: strict
grade: stable

apps:
  text-game-template:
    command: bin/TextGameTemplate
    plugs:
      - desktop
      - desktop-legacy

parts:
  text-game-template:
    plugin: cmake
    source: .
    stage-packages:
      - python3
    build-packages:
      - python3
